### ISSUE TITLE
[arm] 

### ISSUE THREAD

**Issue by the-jojo-jj** [immauss/openvas#42] opened 2021-05-30 12:09 UTC
Hi, everybody..

I have executed:
docker run -d -p 9392:9392 -p 9390:9390 -e GMP=9390 --name openvas -v /var/openvas:/data --name openvas immauss/openvas:latest

but, I've got:
status: Downloaded newer image for immauss/openvas:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

root@odroid:~# uname -a
Linux odroid 4.14.180-178 #1 SMP PREEMPT Wed Sep 2 12:39:45 -03 2020 armv7l armv7l armv7l GNU/Linux

root@odroid:~# docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:33 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:33 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

thanks in advance.

**Comment by immauss** [comment] 2021-06-01 04:41
The latest has not yet been compiled for arm.  
Currently the latest tag build for arm is : armh-20.08.03
I hadn't seen much (any) traffic on them, so I hadn't put much time into building on arm again yet.  If you try to use that tag, I don't think the GMP option is on that image though. 
I'll see if I can get the 21.04 branch to build on my RPi and if it does, I can push that up. (Which is what I did before).

-Scott

**Comment by the-jojo-jj** [comment] 2021-06-01 08:49
Thanks a lot for your time and effort, Scott!

**Comment by immauss** [comment] 2021-06-14 19:46
OK .... I'm trying something new, to hopefully save me some time/pain. buildx. Building for multiple architectures and pushing to docker hub in a single tag, all of the architectures.

Please give this one a try:
immauss/openvas:multi

I must stress.... This is BETA!! I've not done any testing on this yet. There should be an arm64 image and an arm/v7 image with that tag. If I can get this to work, I'll start using buildx as my default to rebuild weekly and fresh multi-arch images.

Thanks,
Scott

**Comment by immauss** [comment] 2021-06-14 19:50
Oh ... and this is the latest 21.04 build.

**Comment by immauss** [comment] 2021-06-27 10:55
So. .... For some reason, when I try to build for armv7, the build fails. I've got the arm64.aarch64 build working, but have not had time to decipher the failure with armv7.

**Comment by immauss** [comment] 2021-06-27 21:49
one of the github repos was failing to download with wget because of a certificate error. I used curl, and it was fine. 
So now ... there is what I hope will be , a valid armv7 tag.

-Scott

**Comment by immauss** [comment] 2021-06-29 22:16
armv7 is now availalbe in :latest. 
Please let me know if you have any issues with it. 

-Scott

**Comment by immauss** [comment] 2021-07-06 05:02
I'm closing this one as it seems to be duplicate of your other issues TS at this point.

**Closed by immauss** 2021-07-06 05:02 UTC
Labels: enhancement
