### ISSUE TITLE
shrink image with alpine

### ISSUE THREAD

**Issue by hacker-h** [immauss/openvas#65] opened 2021-09-21 20:40 UTC
Since openvas is available for alpine, it might be worth to take a look how much effort the switch from debian to alpine would be to shrink down the overall image size.
Maybe somebody also tried this and can give a rough estimate whether it's worth it at all

**Comment by immauss** [comment] 2021-09-21 21:22
What do you mean by 'available for alpine'? Are there packages somewhere for alpine? Please send links. 

I just spent a good deal of time re-writing everything to move from Ubuntu to Debian. The reason for moving to Debian is because that's what the Greenbone Dev team does all their in work on, and I was tired of fighting dependency battles. I lost faith and trust in packagers for openvas a while back when the one I was using caused me to lose about a years worth of data. I was able to restore from backups, but it was a great deal of pain. So now I build from Greenbone release source. I would NOT want to try building from source on Alpine .... 

That said. I do quite a bit to minimize the overall size of the image including building a custom base image with the minimum packages required to operate openvas (it's quite a long list). I then use a two stage build process where I add the dev packages to that base to do the build, then copy the compiled binaries to the base image. Moving to the two stage build actually shrank the image by almost 1G !!

There is also a 600MB of compressed (with xz) tarball with a fresh clean database and all the raw feeds from greenbone, so you can get the image up and running in a few minutes vs an hour.  

Anyway, I'm betting, that even using alpine, the image would not get that much smaller.  Though I could be wrong. The problem is the dependencies eat up a lot of space. 

I did notice, not long ago, that the feed sync pulls the feeds for both 20.08 & 21.04. Since I'm on 21.04 I don't think we need the 20.08 feeds, so I should be able to remove those, and maybe shrink that tarball a little. It's on my TODO list. 

Thanks,
Scott

**Closed** 2021-09-27 05:59 UTC

**Comment by hacker-h** [comment] 2021-09-28 01:06
It is available for alpine in the edge sources:
https://pkgs.alpinelinux.org/package/edge/community/x86_64/openvas

But you are probably right: since most of the image size is dependency driven the base image switch might not be worth the effort.
