### ISSUE TITLE
nasl_pread: Failed to close file descriptor for child process (Operation not permitted)

### ISSUE THREAD

**Issue by DumSkidderik** [immauss/openvas#241] opened 2024-01-02 09:30 UTC
**Describe the bug**
After pulling newest image, scans complete instantly and the below error message fills the logs:
nasl_pread: Failed to close file descriptor for child process (Operation not permitted)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Memory available to OS:  [ 16G ]
 - Container environment used with version: docker

**logs** ( commands assume the container name is 'openvas' )
Please attach the output from one of the following commands:

# docker #
[_openvas_logs.txt]
docker logs openvas > (https://github.com/immauss/openvas/files/13808603/_openvas_logs.txt)

**Comment by immauss** [comment] 2024-01-07 16:40
@DumSkidderik I'm not able to reproduce this .... 
Can you give me any more details about the setup? Also, please verify that the container's path to the targets is good. I usually check this by starting a shell in the container and using nmap to verify the connectivity. 

-Scott

**Comment by anonymous0871** [comment] 2024-01-15 13:09
Hi Scott, I have the same problem.
I scan from cloud server to LAN via zerotier, but without success.
I use your docker-compose file to start container.
Have any suggest

**Comment by immauss** [comment] 2024-01-15 17:36
@anonymous0871 
Can you try with an older tag and see if the problem persists?

**Comment by anonymous0871** [comment] 2024-01-16 07:54
Hi  Scott, I can try, sure, and advise you if I will have success.Thanks for your reply. FlorianoInviato dal mio Galaxy
-------- Messaggio originale --------Da: GE Scott Knauss ***@***.***> Data: 15/01/24  18:36  (GMT+01:00) A: immauss/openvas ***@***.***> Cc: anonymous0871 ***@***.***>, Mention ***@***.***> Oggetto: Re: [immauss/openvas] nasl_pread: Failed to close file descriptor for child process (Operation not permitted) (Issue #241) 
@anonymous0871
Can you try with an older tag and see if the problem persists?

**Comment by anonymous0871** [comment] 2024-01-16 09:12
Hi Scott, no success with an old branch :-(

**Comment by immauss** [comment] 2024-01-16 09:21
How far back did you go? 
What tag? 

There is another issue, that seems similar to me for no reason other than my gut, that started with 22.4.34. The problem did not happen with 22.4.33, so Could you also try that tag? 

Thank you,
-Scott

**Comment by anonymous0871** [comment] 2024-01-18 11:47
Thanks Scott with 22.4.33 all is ok.
Have a good day

**Comment by DumSkidderik** [comment] 2024-01-18 11:53
Sorry for not replying, github got caught in the spam filter!
Confirmed that 22.4.33 works

**Comment by immauss** [comment] 2024-01-18 12:39
Well ....
.
.

That is interesting ....

Thank you. This is VERY helpful ... or it should be. Now I'm I'm just more confused. 

This one might take me some time to work out as I'll have to dedicate some time to it and things are a bit busy around here. For the time being, you're no missing anything serious by continuing to use 22.4.33 until I can work it out. 

Thanks,
-Scott

**Comment by immauss** [comment] 2024-01-22 21:22
This appears to be the same problem as #241. So closing this one. 
Please follow via #241

-Scott

**Closed by immauss** 2024-01-22 21:22 UTC
