### ISSUE TITLE
An error occurs when editing actions in the scan configuration in the latest version 22.4.37

### ISSUE THREAD

**Issue by GavinTan** [immauss/openvas#239] opened 2023-12-29 03:19 UTC
console: 

scanconfigs:1 Uncaught (in promise) $b {name: 'Rejection', message: 'An internal error occurred inside GSA daemon. Diagnostics: Unknown command.', reason: 'error', error: undefined, _xhr: XMLHttpRequest, …}

**Comment by immauss** [comment] 2023-12-29 11:08
@GavinTan This sounds like it is a Greenbone problem, but could you please provide the steps to reproduce this ? Please be as specific as possible including the action you are trying to edit. 

Thank you,
Scott

**Comment by GavinTan** [comment] 2023-12-30 01:22
Clicking on 'actions' in the edit SAN configuration does not display any content, and then the page console shows the error mentioned above.

![image](https://github.com/immauss/openvas/assets/10555093/f49d032a-b28e-46ea-b81b-78e0a6767560)

**Comment by immauss** [comment] 2024-01-01 12:09
Looks like I was not pulling the latest bits from Greenbone on the GSA rebuilds. It will be resolved in the version I'm pushing later today. 

Thanks for finding and reporting this.

Happy New Year !

-Scott

**Comment by immauss** [comment] 2024-01-01 18:27
Resolved with 22.4.38

**Closed by immauss** 2024-01-01 18:27 UTC
