### ISSUE TITLE
can't add new user

### ISSUE THREAD

**Issue by sergeymeleschenko** [immauss/openvas#204] opened 2023-07-19 12:40 UTC
can't add new users on the web. The button save doesn't work.

**Comment by immauss** [comment] 2023-07-19 20:01
Confirmed ... This is weird. 
It seems to work fine with 2.4.20, but with the latest, it fails.  This is odd because they should be identical except for the database updates. Regardless, there is yet another gvmd update from GB, so there will be a new version shortly. Let's see if that one has the same problem. 

In the mean time, if you need to create users, please use 2.4.20 tag. 

Thanks,
Scott

**Comment by immauss** [comment] 2023-07-19 20:22
ok .. the betat with the latest seems to have the same issue. The sounds like a GB issue as none of my code has changed, and there's nothing I could do that should make this sort of problem anyway .... 
Though, now that I've said that ..... 

I'm goign to ping GB via forums.  I'll let you know here what happens. 

-Scott

**Comment by sergeymeleschenko** [comment] 2023-07-20 09:41
Great , thanks. But in 22.4.20 the same problem.

> ok .. the betat with the latest seems to have the same issue. The sounds like a GB issue as none of my code has changed, and there's nothing I could do that should make this sort of problem anyway .... Though, now that I've said that .....
> 
> I'm goign to ping GB via forums. I'll let you know here what happens.
> 
> -Scott

Great , thanks. But in 22.4.20 the same problem.

**Comment by immauss** [comment] 2023-07-20 15:37
So ... going back, it looks like this might be a problem with the newer version of gsa (22.5.0). 
In the mean time, you can use this:

docker exec -it -u gvm openvas gvmd --role="Admin" --create-user="$USERNAME" --password="$PASSWOR│·····
D"

Thanks,
Scott

**Comment by immauss** [comment] 2023-07-21 05:58
GB says they've already fixed this in a future release of gsa.
https://github.com/greenbone/gsad/issues/137

**Comment by immauss** [comment] 2023-08-02 22:45
This should be resolved in the latest images.

**Closed** 2023-08-02 22:50 UTC
